[2024-10-15T14:05:58.638+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T14:05:58.908+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_data_sells_directory manual__2024-10-15T14:05:27.576750+00:00 [queued]>
[2024-10-15T14:05:58.943+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T14:05:59.079+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_data_sells_directory manual__2024-10-15T14:05:27.576750+00:00 [queued]>
[2024-10-15T14:05:59.087+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-15T14:05:59.532+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data_sells_directory> on 2024-10-15 14:05:27.576750+00:00
[2024-10-15T14:05:59.580+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: etl_update_stock_ferrimac.extract_data_sells_directory manual__2024-10-15T14:05:27.576750+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-10-15T14:05:59.651+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: etl_update_stock_ferrimac.extract_data_sells_directory manual__2024-10-15T14:05:27.576750+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-10-15T14:05:59.866+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-15T14:05:59.924+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2024-10-15T14:05:59.908+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_data_sells_directory', 'manual__2024-10-15T14:05:27.576750+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmp4_jqa_ca']
[2024-10-15T14:05:59.970+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask extract_data_sells_directory
[2024-10-15T14:05:59.936+0000] {standard_task_runner.py:72} INFO - Started process 179 to run task
[2024-10-15T14:06:01.430+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_data_sells_directory manual__2024-10-15T14:05:27.576750+00:00 [running]> on host 2296928c39b5
[2024-10-15T14:06:06.794+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_data_sells_directory' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T14:05:27.576750+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T14:05:27.576750+00:00'
[2024-10-15T14:06:06.815+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T14:06:07.145+0000] {logging_mixin.py:190} INFO - The file 'ventas_unidades.xlsx' was not found in the sells directory.
[2024-10-15T14:06:07.161+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-15T14:06:07.303+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T14:06:07.305+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_update_stock_ferrimac, task_id=extract_data_sells_directory, run_id=manual__2024-10-15T14:05:27.576750+00:00, execution_date=20241015T140527, start_date=20241015T140558, end_date=20241015T140607
[2024-10-15T14:06:07.786+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-15T14:06:09.195+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T14:06:09.206+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
