[2024-10-16T02:21:51.542+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T02:21:51.783+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T02:21:51.920+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T02:21:51.932+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-16T02:21:52.417+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task_api> on 2024-10-15 00:00:00+00:00
[2024-10-16T02:21:52.559+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-16T02:21:52.730+0000] {standard_task_runner.py:72} INFO - Started process 102 to run task
[2024-10-16T02:21:52.608+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_task_api', 'scheduled__2024-10-15T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmps0vs_uax']
[2024-10-16T02:21:52.839+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask extract_task_api
[2024-10-16T02:21:53.564+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-15T00:00:00+00:00 [running]> on host 2296928c39b5
[2024-10-16T02:22:01.745+0000] {job.py:229} INFO - Heartbeat recovered after 10.88 seconds
[2024-10-16T02:22:18.973+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_task_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-15T00:00:00+00:00'
[2024-10-16T02:22:19.005+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T02:22:21.625+0000] {logging_mixin.py:190} INFO - Current dolar rates: 979.498605 ARS
[2024-10-16T02:22:21.632+0000] {logging_mixin.py:190} INFO - base_datos/inventario/data_price.csv
[2024-10-16T02:22:21.673+0000] {logging_mixin.py:190} INFO - Record of day 2024-10-16 just exist. Not add again.
[2024-10-16T02:22:21.676+0000] {python.py:240} INFO - Done. Returned value was:          date       price
0  2024-10-15  979.763503
1  2024-10-16  979.498605
[2024-10-16T02:22:22.420+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T02:22:22.423+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_update_stock_ferrimac, task_id=extract_task_api, run_id=scheduled__2024-10-15T00:00:00+00:00, execution_date=20241015T000000, start_date=20241016T022151, end_date=20241016T022222
[2024-10-16T02:22:22.644+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-16T02:22:22.850+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-16T02:22:22.856+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-16T03:37:49.833+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T03:37:49.970+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T03:37:50.040+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T03:37:50.053+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-16T03:37:50.317+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task_api> on 2024-10-15 00:00:00+00:00
[2024-10-16T03:37:50.414+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=125) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-16T03:37:50.440+0000] {standard_task_runner.py:72} INFO - Started process 144 to run task
[2024-10-16T03:37:50.466+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_task_api', 'scheduled__2024-10-15T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmpnm3v59y2']
[2024-10-16T03:37:50.495+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask extract_task_api
[2024-10-16T03:37:51.358+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-15T00:00:00+00:00 [running]> on host 1632cd2c9696
[2024-10-16T03:38:01.485+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_task_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-15T00:00:00+00:00'
[2024-10-16T03:38:01.525+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T03:38:03.443+0000] {logging_mixin.py:190} INFO - Current dolar rates: 979.401102 ARS
[2024-10-16T03:38:03.464+0000] {logging_mixin.py:190} INFO - base_datos/inventario/data_price.csv
[2024-10-16T03:38:03.626+0000] {logging_mixin.py:190} INFO - Record of day 2024-10-16 just exist. Not add again.
[2024-10-16T03:38:03.628+0000] {python.py:240} INFO - Done. Returned value was:          date       price
0  2024-10-15  979.763503
1  2024-10-16  979.498605
[2024-10-16T03:38:04.176+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T03:38:04.179+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_update_stock_ferrimac, task_id=extract_task_api, run_id=scheduled__2024-10-15T00:00:00+00:00, execution_date=20241015T000000, start_date=20241016T033749, end_date=20241016T033804
[2024-10-16T03:38:04.309+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-16T03:38:04.867+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-16T03:38:04.872+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-16T04:51:42.028+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T04:51:42.113+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T04:51:42.215+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T04:51:42.217+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-16T04:51:42.317+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task_api> on 2024-10-15 00:00:00+00:00
[2024-10-16T04:51:42.355+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-16T04:51:42.384+0000] {standard_task_runner.py:72} INFO - Started process 183 to run task
[2024-10-16T04:51:42.396+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_task_api', 'scheduled__2024-10-15T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmpyupp2_s3']
[2024-10-16T04:51:42.412+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask extract_task_api
[2024-10-16T04:51:42.782+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-15T00:00:00+00:00 [running]> on host 5eb5ec31bb35
[2024-10-16T04:51:49.525+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_task_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-15T00:00:00+00:00'
[2024-10-16T04:51:49.529+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T04:51:50.507+0000] {logging_mixin.py:190} INFO - Error getting price: 401, {"message":"No API key found in request"}
[2024-10-16T04:51:50.514+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/obtain_currency.py", line 39, in append_to_data_price
    file_path = base_path.joinpath(file)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pathlib.py", line 717, in joinpath
    return self.with_segments(self, *pathsegments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pathlib.py", line 385, in with_segments
    return type(self)(*pathsegments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pathlib.py", line 1162, in __init__
    super().__init__(*args)
  File "/usr/local/lib/python3.12/pathlib.py", line 373, in __init__
    raise TypeError(
TypeError: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'NoneType'
[2024-10-16T04:51:50.572+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_update_stock_ferrimac, task_id=extract_task_api, run_id=scheduled__2024-10-15T00:00:00+00:00, execution_date=20241015T000000, start_date=20241016T045142, end_date=20241016T045150
[2024-10-16T04:51:50.614+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T04:51:50.615+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task extract_task_api (argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'NoneType'; 183)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/obtain_currency.py", line 39, in append_to_data_price
    file_path = base_path.joinpath(file)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pathlib.py", line 717, in joinpath
    return self.with_segments(self, *pathsegments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pathlib.py", line 385, in with_segments
    return type(self)(*pathsegments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pathlib.py", line 1162, in __init__
    super().__init__(*args)
  File "/usr/local/lib/python3.12/pathlib.py", line 373, in __init__
    raise TypeError(
TypeError: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'NoneType'
[2024-10-16T04:51:50.691+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-16T04:51:51.071+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T04:51:51.075+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
